-- create table
CREATE TABLE IF NOT EXISTS public.product
(
    id                      UUID UNIQUE         DEFAULT uuid_generate_v4(),
    sku                     VARCHAR(100) UNIQUE DEFAULT NULL,
    name                    VARCHAR(255)        DEFAULT NULL,
    short_description       VARCHAR(1000)       DEFAULT NULL,
    description             VARCHAR(4000)       DEFAULT NULL,
    "order"                 INTEGER             DEFAULT NULL,
    status_id               UUID                DEFAULT NULL REFERENCES public.product_status (id),
    link                    VARCHAR(255) UNIQUE DEFAULT NULL,

    regular_price           REAL                DEFAULT NULL,
    sale_price              REAL                DEFAULT NULL,
    factory_price           REAL                DEFAULT NULL,
    is_taxable              BOOLEAN             DEFAULT true,

    quantity                INTEGER             DEFAULT NULL,
    return_to_stock_date    TIMESTAMP           DEFAULT NULL,
    is_track_stock          BOOLEAN             DEFAULT TRUE,

    shipping_class_id       UUID                DEFAULT NULL REFERENCES public.shipping_class (id),
    shipping_weight         REAL                DEFAULT NULL,
    shipping_width          REAL                DEFAULT NULL,
    shipping_height         REAL                DEFAULT NULL,
    shipping_length         REAL                DEFAULT NULL,

    seo_title               VARCHAR(100)        DEFAULT NULL,
    seo_description         VARCHAR(4000)       DEFAULT NULL,
    gtin                    VARCHAR(50)         DEFAULT NULL,
    google_product_category VARCHAR(50)         DEFAULT NULL,
    google_product_type     VARCHAR(100)        DEFAULT NULL,

    created_at              TIMESTAMP           DEFAULT NOW() NOT NULL,
    created_by              UUID                DEFAULT NULL REFERENCES public.user (id),
    updated_at              TIMESTAMP           DEFAULT NOW() NOT NULL,
    updated_by              UUID                DEFAULT NULL REFERENCES public.user (id),

    CONSTRAINT product_id_pkey PRIMARY KEY (id)
);

-- ownership, index and comment
ALTER TABLE public.product
    OWNER TO postgres;
CREATE UNIQUE INDEX product_id ON public.product (id);
CREATE UNIQUE INDEX product_sku ON public.product (sku);
CREATE UNIQUE INDEX product_link ON public.product (link);
COMMENT ON TABLE public.product IS 'Product information';

-- demo data
insert into public.product (id, sku, name, short_description, description, "order", status_id, regular_price,
                            sale_price, quantity, shipping_weight, shipping_length, shipping_width, shipping_height,
                            gtin, link, google_product_category, google_product_type, shipping_class_id)
VALUES ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd382500', 'IS48LUXOR', '48″ Luxor Island Range Hood',
        'Radiant, lustrous, and on the cutting edge of modernity, the Luxor Island Range Hood will make a striking statement in any kitchen.',
        'Radiant, lustrous, and on the cutting edge of modernity, the Futuro Futuro 48 inch Luxor Island Range Hood will make a striking statement in any kitchen. With its sleek, gleaming exterior and bright white perimeter light, this luxury range hood is reminiscent of an extraterrestrial spacecraft- and it has the advanced technology to boot. This unique range hood is composed of an illuminated glass perimeter that is lit entirely from within, and specialized stainless steel that prevents smudging or streaks and leaves only a glossy, finger-print free finish. This unique range hood possesses cutting-edge industrial technology that optimizes air filtration performance. This suspended range hood will keep your kitchen cool and contaminant free with its exclusive perimeter suction system, which redirects the airflow from the center of the unit to the mesh filters along the edges of the exhaust hood, providing a cleaner look, increasing suction, and cutting ambient noise. This professional style range hood further improves upon its superb performance by entrapping airborne grease and other culinary contaminants with its designer grease filters, which are concealed behind its illuminated glass panels to provide a clean, streamlined design. This unique range hood possesses four different airflow speeds, energy efficient fluorescent lights, and an extendable chimney that can be easily lengthened between 25 and 48 inches for perfect placement over any kitchen island range. This unique range hood makes regular maintenance easy with its automated reminders that indicate when it’s time to clean the grease filters in the dishwasher to maintain optimal performance. This Italian range hood also possesses a delayed shut-off function, which keeps the ventilation hood on even after you have finished cooking until the removal of odors, grease, and impurities from the air has been completed. Customers may purchase this kitchen range hood with the choice of a ducted or ductless exhaust vent, and all Futuro Futuro ventilation hoods come with a one year US standard and two year parts warranty. Show-stoppingly gorgeous and expertly crafted, the Italian made 36 inch Luxor island mount range hood is perfect for kitchen owners seeking a powerful kitchen accessory with exclusive style. sku: IS48LUXOR',
        1040, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 4000, 2695, 5, 140, 51, 40, 26, '022099539230',
        '48-luxor-island-range-hood', 684, 'Kitchen Range Hood > Island Mount > Glass > 48-inch',
        'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd382501', 'WL36MELARA', '36″ Melara Wall Range Hood',
        'Comfortable yet sophisticated, the 36″ Melara country style range hood is a beautifully crafted Italian kitchen accessory that will perfectly complement more traditionally styled kitchens',
        'Comfortable yet sophisticated, the Futuro Futuro 36 inch Melara Wall Range Hood is a beautifully crafted Italian range hood that will feel right at home in any traditional or country style kitchen. This steel range hood is composed of solid white oak and high quality steel that has been specially coated in a durable and unique enamel that can serve as either the finished exterior or as a base coat for another paint color. Kitchen owners can easily alter the exterior of this luxury range hood by using any kind of paint, including oil-based, water-based, or sprays, to coat the exhaust hood’s steel body to match or complement other colors in the kitchen- with no primer needed. The wooden accents on this traditional style range hood come unstained, so kitchen owners may perfectly match them to existing kitchen cabinetry. This modern range hood offers user-friendly features, including its three different airflow speeds, energy efficient LED lights, and an easy to use slider control. Robust and efficient, this powerful range hood uses cutting-edge technology to quickly remove steam, smoke, and odors from the air while maintaining whisper quiet noise levels, thanks to Futuro Futuro’s innovative blower and exclusive sound absorbing technology. This wood range hood also contains dishwasher safe, designer metal mesh filters that specifically target the capture of oil and grease, keeping it from collecting on your kitchen surfaces. Regular maintenance is straightforward with this country style range hood’s convenient features and functionality. This designer range hood has automated reminders that are programmed to routinely indicate when it’s time to clean the filters in the dishwasher to maintain optimal performance. Additionally, this unique range hood’s convenient delayed shut-off function keeps the exhaust hood on until all odors, grease, and impurities have been removed from the air, allowing users to focus their attention elsewhere after cooking. Customers may purchase this kitchen range hood with the choice of a ducted or ductless exhaust vent, dependent on their existing kitchen’s build. All Futuro Futuro ventilation hoods come with a one year US standard and two year parts warranty. Stately yet homey, the 36 inch Melara wall mount range hood is perfect for kitchen owners who prefer traditional styles but require a modern performance. sku: WL36MELARA',
        560, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 2050, 1395, 8, 67, 48, 40, 31, '022099539612',
        '36-melara-wall-range-hood', 684, 'Kitchen Range Hood > Wall Mount > Stainless Steel > 36-inch',
        'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd382502', 'IS48POSITANO', '48″ Positano Island Range Hood',
        'Futuro Futuro’s Positano Island Range Hoods are made with high-end stainless steel materials and premium craftsmanship with a simple design that will look great in any kitchen.',
        'Futuro Futuro’s Positano series of island range hoods have a simple design that will look great in any kitchen. These hoods with the highest grade of Stainless Steel, patented technology, and premium Italian craftsmanship. The Positano series puts an emphasis on form and function, ease of use, and simplicity. The Stainless Steel used in all Futuro Futuro products is of the highest quality for kitchen hoods, AISI 304. What makes AISI 304 Stainless Steel perfect for kitchen hoods is the high proportion of Chromium which gives it a high resistance to corrosion and rust. This helps the material stand up to the grime that is inevitable when regularly using a kitchen hood. The main piece of patented technology that you will notice immediately is the sound-absorbing chamber. By advancing technology in sound absorption for kitchen hoods Futuro Futuro is able to keep their products powerful yet still quiet for a residential kitchen. By using a powerful blower motor that would simply be too loud without their patented sound-absorbing chamber gives you the power of a commercial hood without all the noise. To make this simple hood even easier to use they added an illuminated electronic control panel to control every function of the hood. You can easily set a delayed shut off timer so the hood will continue to run for 15 minutes after shutting it off. This lets you turn the hood off as soon as your done and it will keep running to ensure the air in your kitchen is clean. These control panels even come equipped with a reminder for when it’s time to clean the designer filters that come standard! The Positano Island Range Hoods comes equipped with four LED lights that perfectly illuminate your cooking area. The four lights are positioned in the corners of the hood to create a central point of light over your stove top that melds out to your countertop. These LED lights are long lasting and energy efficient bulbs to keep your costs and maintenance as low as possible. The goal in designing the Positano series was to create a simple design that perfectly combined form and function. Through patented technology, premium Italian craftsmanship, and high quality materials Futuro Futuro created a hood that is built to last and will always look great. sku: IS48POSITANO',
        1010, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 3400, 2295, 35, 110, 51, 40, 25, '022099539247',
        '48-positano-island-range-hood', 684, 'Kitchen Range Hood > Island Mount > Stainless Steel > 48-inch',
        'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd382503', 'IS48STREAMLINE-WHT', '48″ Streamline Island Range Hood',
        'With its sleek, angular characteristics and durable build, this slim stainless steel range hood is the perfect choice for modern kitchen owners with classic tastes',
        'With its sleek, angular characteristics and durable build, the Futuro Futuro 48 inch Streamline Island Range Hood lends a modern look to your kitchen while ensuring a cleanly feeling and environment. By keeping the classic range hood shape but slimming the front of the exhaust hood down to less than two inches wide, this luxury range hood has achieved an impressive balance between modern and traditional styles. This slim range hood also sports a white LED light accent strip across its front, enhancing this modern range hood’s already slim design and sophisticated appearance. This suspended range hood is built from the highest-grade 304 stainless steel, offers energy efficient LED lighting, and a built in, illuminated, electric control panel. The extendable chimney of this ceiling range hood is easily adjustable, and can be lengthened between 25 and 48 inches for perfect placement over any kitchen island range. This stainless steel range hood uses cutting-edge technology to optimize performance and ease of use. This powerful range hood works to keep your kitchen cool and contaminant free by quickly removing steam, smoke, and odors from the air while maintaining whisper quiet noise levels, thanks to innovative sound absorbing technology exclusive to Futuro Futuro. With its four different airflow suction speeds and its removable, dishwasher-safe, metal filters, this traditional style range hood thoroughly entraps grease from the air. This contemporary range hood also makes regular maintenance easy with its automated reminders that indicate when it’s time to clean the designer metal filters in the dishwasher to maintain optimal performance. This Italian range hood possesses the convenient delayed shut-off function, which keeps the ventilation hood on even after you have finished cooking until the removal of odors, grease, and impurities from the air has been completed. Customers may purchase this kitchen range hood with the choice of a ducted or ductless exhaust vent, and all Futuro Futuro ventilation hoods come with a one year US standard and two year parts warranty. The 48 inch Streamline island mount range hood possesses a beautiful exterior, an ultra slim design, and an impressive filtration apparatus, making it the perfect choice for modern kitchen owners with classic tastes. sku: IS48STREAMLINE-WHT',
        1000, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 3700, 2495, 24, 113, 51, 40, 23, '022099539261',
        '48-streamline-island-range-hood', 684, 'Kitchen Range Hood > Island Mount > Stainless Steel > 48-inch',
        'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd382504', 'IS42ACQUA-GLS', '42″ Acqualina Glass Island Range Hood',
        'The 42″ Futuro Futuro glass and stainless steel island range hood blends professional quality with contemporary style. Easy to maintain, this hood is perfect for any modern kitchen.',
        'With high quality performance and a sophisticated sense of style, Futuro Futuro’s Acqualina 42 inch curved glass island mount range hood is the perfect choice for kitchen owners who are looking for a professional grade range hood with an elegant, contemporary style. This beautiful three and a half foot wide island range hood is comprised of tempered, transparent glass and corrosion-resistant 304 stainless steel, which gives the hood an enduring sleek and lustrous look that will complement any modern style kitchen. This modern range hood is designed to mount on the ceiling and has an adjustable chimney to accommodate various ceiling heights. Accessories like the optional chimney extension are available for kitchens with especially high ceilings. This luxury range hood has four different airflow speeds and features built-in, energy-efficient LED lighting, designer filters, an illuminated control panel, and the option to purchase the hood with your choice of a ducted or ductless exhaust vent. Within the interior, this contemporary range hood boasts a powerful air ventilation system while maintaining whisper-quiet noise levels due to superior sound-absorbing technology exclusive to Futuro Futuro. This kitchen range hood''s smart technology makes appliance clean up and maintenance easy with programmed prompts that recurrently remind you when it’s time to clean the dishwasher safe, metal mesh filters included in your hood purchase. This island mount range hood also features a delayed shut-off function to ensure the complete removal of smoke, steam, and odors that may linger in the air after you have finished cooking. All Futuro-Futuro hoods come with detailed installation and maintenance manuals. With a one year US standard and two year parts warranty, the 42 inch Italian-crafted Acqualina glass and stainless steel island range hood is not to be passed up. Technical staff are happy to assist with questions that may arise during installation or during daily use. sku: IS42ACQUA-GLS',
        530, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 3400, 2295, 0, 117, 48, 40, 27, '022099538615',
        '42-acqualina-glass-island-range-hood', 684, 'Kitchen Range Hood > Island Mount > Glass > 42-inch',
        'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'),
       ('a0eebc99-9c0b-4ef8-bb6d-6bb9d3837887', 'WL36LINEA', '36″ Linea Wall Range Hood',
        'Elevate your kitchen with the Futuro Futuro 36-inch Linea Wall Range Hood. Its sleek stainless steel design, energy-efficient LED lights, and tactile black trim add modern elegance. With four airflow speeds and a quiet, powerful blower, it offers precise ventilation. Easy maintenance, smart technology, and a warranty ensure lasting quality. Upgrade your kitchen with style and performance.',
        'Elevate the aesthetics and functionality of your kitchen with the Futuro Futuro 36-inch Linea Wall Range Hood. Combining contemporary design with cutting-edge technology, this range hood is a masterpiece of form and function. \nMeasuring under two inches in thickness across its front, this range hood''s high-grade stainless steel body gives it a sleek, modern appearance. The elegant exterior is further accentuated by a luminous, energy-efficient white LED lights, which illuminates your cooking area. \nThe smooth, lustrous finish of the black trim adds depth and texture to the range hood''s facade, creating a tactile experience that enhances the overall ambiance of your kitchen. Its minimalist design allows it to harmonize effortlessly with a variety of interior styles, from modern and minimalist to classic and eclectic. \nWith four different airflow speeds, this range hood ensures that you have precise control over ventilation, regardless of your cooking needs. The blower, with its impressive 940 CFM power, efficiently removes smoke, steam, and odors from the air, all while operating quietly thanks to Futuro Futuro''s advanced blower technology. \nMaintenance is a breeze with the Futuro Futuro Line Black Wall Range Hood. Its dishwasher-safe designer metal filters can be effortlessly cleaned, ensuring that your kitchen air remains fresh and free of grease. The electronic control panel provides user-friendly operation, and the integrated smart technology includes a delayed shut-off function. This function keeps the range hood running after you''ve finished cooking to ensure the complete removal of odors and impurities from the air. \nFuturo Futuro is committed to quality, offering a one-year US standard warranty along with an additional two-year parts warranty on all its range hoods. Rest assured that your investment is protected. \nUpgrade your kitchen with the Futuro Futuro 36-inch Line Black Wall Range Hood and experience the perfect blend of style and performance. sku: WL36LINEA',
        10, 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 2650, 1795, 10, NULL, NULL, NULL, NULL, '703168132766',
        '36-linea-wall-range-hood', 684, 'Kitchen Range Hood > Wall Mount > Stainless Steel > 36-inch',
        'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12');

-- get data
select * from public.product;