-- drop table if exists public.stock_quantity;
drop table if exists public.stock_quantity;

-- create table
CREATE TABLE IF NOT EXISTS public.stock_quantity
(
    id           UUID UNIQUE DEFAULT uuid_generate_v4() NOT NULL,

    product_id   UUID        DEFAULT NULL,
    quantity     INTEGER     DEFAULT NULL,
    warehouse_id UUID        DEFAULT NULL,

    created_at   TIMESTAMP   DEFAULT NOW()              NOT NULL,
    created_by   UUID        DEFAULT NULL,
    updated_at   TIMESTAMP   DEFAULT NOW()              NOT NULL,
    updated_by   UUID        DEFAULT NULL,

    CONSTRAINT stock_quantity_pkey PRIMARY KEY (id)
);

-- ownership and index
ALTER TABLE public.stock_quantity OWNER TO postgres;
CREATE INDEX stock_quantity_id ON public.stock_quantity (id);
CREATE INDEX stock_quantity_product_id ON public.stock_quantity (product_id);
CREATE INDEX stock_quantity_warehouse_id ON public.stock_quantity (warehouse_id);
CREATE INDEX stock_quantity_updated_at ON public.stock_quantity (updated_at);

-- add comments
COMMENT ON TABLE public.stock_quantity IS 'stock_quantity table';
COMMENT ON COLUMN public.stock_quantity.id IS 'Unique identifier';
COMMENT ON COLUMN public.stock_quantity.product_id IS 'Product identifier';
COMMENT ON COLUMN public.stock_quantity.quantity IS 'Quantity of product';
COMMENT ON COLUMN public.stock_quantity.warehouse_id IS 'Warehouse identifier';
COMMENT ON COLUMN public.stock_quantity.created_at IS 'Creation date';
COMMENT ON COLUMN public.stock_quantity.created_by IS 'Creator identifier';
COMMENT ON COLUMN public.stock_quantity.updated_at IS 'Update date';
COMMENT ON COLUMN public.stock_quantity.updated_by IS 'Updater identifier';

-- auto update updated_at
CREATE OR REPLACE TRIGGER stock_quantity_updated_at
    BEFORE UPDATE
    ON public.stock_quantity
    FOR EACH ROW
    EXECUTE FUNCTION update_update_at_column();

-- auto set created_by
CREATE OR REPLACE TRIGGER stock_quantity_created_by
    BEFORE INSERT
    ON public.stock_quantity
    FOR EACH ROW
    EXECUTE FUNCTION set_created_by_if_null();

-- auto set updated_by
CREATE OR REPLACE TRIGGER stock_quantity_updated_by
    BEFORE INSERT
    ON public.stock_quantity
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_by_if_null();

-- default data
INSERT INTO public.stock_quantity (product_id, quantity, warehouse_id)
VALUES
    ((select id from public.product_info where sku = 'IS48LUXOR'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MELARA'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48POSITANO'),41,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48STREAMLINE-WHT'),26,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS42ACQUA-GLS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36INTEGRA-WHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36LUXOR'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36MOONCRYS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36MOONINOX'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36VENICE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36LOMBARDY-WHT'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36LOMBARDY-BLK'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36JUPITER-GLS'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36STREAMLINE-WHT'),19,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36POSITANO'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36POSITANO-FS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48EUROPE'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36LOFT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-ALFA'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-FORTUNA'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-SNOW'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36CONNECTICUT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS28ELLIPSO'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS28MODERNO'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-AUTUMN'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24LOMBARDY-BLK'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24LOMBARDY-WHT'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24SPIRIT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24MOONINOX'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS16LOFTCTM'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS16LOFT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-ZEBRA'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-ORION'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-NEWYORK'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-MOTION'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-FROST'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-SNOW'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS54SKYLIGHT'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS84EUROPE-STN'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48STREAMLINE-WHT'),29,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48POSITANO'),19,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48MAGNUS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48LUXOR'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48QUEST-BLK'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48QUEST-WHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48CAPRI'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36SOLARIS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36ACQUA-GLS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36EDGE-WHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LOMBARDY-BLK'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LOMBARDY-WHT'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36ACQUA-INOX'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36INTEGRA-WHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MOONCRYS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MOONINOX'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36VENICE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MYSTIC-GLS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MYSTIC-INOX'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36STREAMLINE-WHT'),27,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36JUPITER-GLS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LINEARE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36RAZOR'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36WAVEBLK'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36DIAMOND'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36BLKDIAM'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36QUEST-BLK'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36RAINBOW'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36CAPRI'),26,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36IDEA'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MAGNUS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36PORTLAND'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36PORTLAND-PLUS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36CONNECTICUT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36BRIDGEPORT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36ORCHID'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24MODERNO'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24AMALFI'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24LOMBARDY-WHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24LOMBARDY-BLK'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24LINEARE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL14JUPITER-LT'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL14JUPITER'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24MOONINOX'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24VENICE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24STREAMLINE-WHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24CAPRI'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24SPIRIT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL22RAVENNA'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30ACQUA-GLS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30MOONCRYS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL22INSERT-BAF'),17,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL32INSERT'),22,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-FORTUNALED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-ALFALED'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-FROSTLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-SNOWLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-EMPIRELED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-MOTIONLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-ORIONLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL39MUR-SNOWLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-RBK'),899,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-WIRELESS'),972,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARBR6'),58,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARBR8'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-METALFILTER'),656,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXTIS'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-MURPEARL'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXTWS'),40,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXTWR'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-HALOBULB'),19,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-HALOFXRND'),39,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-HALOFXSQ'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-MINIHALO'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-FLRBULB'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-BACKSPL'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-GLSJUPITERIS'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-GLSJUPITERWL'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-36PANELLOFT'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-CON850'),14,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-FAB960'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-MIM850'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-STP960'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36AMALFI'),64,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36GULLWING-WHT'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36GULLWING-BLK'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36WAVEWHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36SHADE'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL26PEARL-BLK'),18,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL26PEARL-WHT'),14,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24AMALFI'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARBSQ'),100,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-AUTUMNLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS30PEARL-WHT'),11,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS30PEARL-BLK'),13,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36POSITANO'),39,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48SHADE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS42MOONCRYS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36ACQUA-GLS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-SPACE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL22INSERT'),57,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36EUROPE'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS72EUROPE-STN'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-GLOWLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-MOONLIGHTLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-NEWYORKLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-ZEBRALED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL39MUR-ALFALED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL39MUR-FORTUNALED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-LUXWALL'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXTIR'),15,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-EMPIRELED'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-GLOWLED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-MOONLIGHTLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-MOTIONLED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-NEWYORKLED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-ORIONLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-ZEBRALED'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-AUTUMNLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-GLOWLED'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-MOTIONLED'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-NEWYORKLED'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-ORIONLED'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-ZEBRALED'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-ALFALED'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-FORTUNALED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-SNOWLED'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS38SKYLIGHT'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL42INSERT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-BLOWER4'),813,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-LUXISLAND'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MASSACHUSETTS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36VERMONT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-MOONLIGHT'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-MOONLIGHTLED'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LUXOREQUO'),34,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-ECHOLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-ECHOLED'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-ECHOLED'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36FLORARED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36FLORAGREEN'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-GLEURO48'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-GLEURO36'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-GLSEUROSHELF'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL16LOFT'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36BOSTON'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36CAMBRIDGE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-METROLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-METROLED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-METROLED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36LIVORNO'),15,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LIVORNO'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36MINIMALWHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MINIMAL-WHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48LINEARE'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-EMPIRELED'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48MARINO'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24SHADE'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-MAYFLOWERLED'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-MAYFLOWERLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-SERENITYLED'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-SERENITYLED'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL27MUR-SERENITYLED'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24MOONCRYS'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL32INSERT-BAF'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS34MUR-MAYFLOWERLED'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24STREAMLINE-BLU'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36MARINO'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-ALFALED'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-RCRS'),11,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-RRCF'),16,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-LED-INCBULB-CW'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-LED-INCBULB-WW'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-SNOWLED'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS27MUR-FORTUNALED'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS69STREAMLINE'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30SHADOW-BLK'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30SHADOW-WHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36VITTORIA'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL34FOLIO-BLK'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL34FOLIO-WHT'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-FLRBULB48'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS40VITTORIA'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36SAVONA-INOX'),43,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36SAVONA-WHT'),39,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL24RACCOLTA'),34,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30RACCOLTA'),14,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36DECORSA'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36VIALE-BLK'),27,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48VIALE-BLK'),32,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36VIALE-WHT'),24,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48VIALE-WHT'),33,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS60SILVANA'),25,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS60RECANO'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS40RECANO'),11,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS19NATALIE'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36TACTIO'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36TRANS-BLK'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-SILENT-DUCTLESS'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24ARENA-INOX'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24ARENA-BLK'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS24ARENA-CR'),14,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS21DOME-BLK'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS21DOME-IRON'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS21DOME-WHT'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS40MONOLITH'),24,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS21DOME-BRS'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS21DOME-CR'),22,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS23HALO'),29,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS30ORBIT-BLK'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS30ORBIT-INOX'),13,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48PERIMETER-WHT'),18,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48PERIMETER-INOX'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36TRANS-CEM'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARB-A'),49,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS14JUPITER-WHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS14JUPITER-LT'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS14JUPITER'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36EVO'),-99,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-STRINGS-6'),87,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-STRINGS-4'),85,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36SLIDE'),23,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL46SLIDE'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-SHELF-EUROPE'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-LIFTGATE'),97,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-INSIDEDELIVERY'),79,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS14JUPITER-BLK'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36POSITANO-BLK'),17,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-EXT-MURWL'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36POSITANO-BLK'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS16LOFT-BLK'),3,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS69STREAMLINE-LH'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS69STREAMLINE-RH'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-ADAPTER'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-MAGICSTEEL'),67,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-STRINGS-2'),98,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-SHELF-L'),5,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30KELVIN-BLK'),50,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30KELVIN-INOX'),51,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL30SLIDE'),20,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36GABI'),13,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36BALANCE-CHR'),19,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36BALANCE-WHT'),18,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36BALANCE-BLK'),29,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-STRINGS-8'),93,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36QUEST-WHT'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS69TURO-BLK'),6,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36TURO-BLK'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36TURO-INOX'),14,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS36TRIM-WHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36FANO-GM'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48FANO-GM'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LORENZO-BLK'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS14JUPITER-CPR'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS14JUPITER-GLD'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36CAMINO-GM'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36CASCADE'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36KNOX-GM'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36COUNTER-GM'),4,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48COUNTER-GM'),2,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36SPHINX'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48SPHINX'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36PYRAMID'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48ALINA-WHT'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36CASTLE'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48CASCADE'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48CASTLE'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARB-ART'),45,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48KNOX-BLK'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS50STEALTH-BLK'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36COUNTRY'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48COUNTRY'),0,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36SPLASH-BLK'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36SPLASH-WHT'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36RAVEN-BLK'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS40MAGNOLIA'),20,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL20CAMPANA-CPR'),1,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36ARTTEMPO-WHT'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48ARTTEMPO-WHT'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36NOVA-GM'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-MCIF'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-24NOVA-SHELF'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48TURO-INOX'),12,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48HORIZON-BLK'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS63HORIZON-BAR'),9,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS63HORIZON-SHELF'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'IS48TURO-BLK'),10,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36FLIPPER'),19,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL48FLIPPER'),19,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36LINEA'),7,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'WL36AESTHETICS-BLK'),8,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARB-G'),18,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARB-HORIZON'),20,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARB-FLIPPER'),18,(SELECT id FROM public.warehouse LIMIT 1)),
    ((select id from public.product_info where sku = 'AC-CARB-MAGNOLIA'),20,(SELECT id FROM public.warehouse LIMIT 1));

-- get data
select * from public.stock_quantity;


